use os.IsPermission and os.IsNotExist in writeErr, to handle these errors properly
taruti/sftpd pull request #6
Opened 2017-06-30 04:34 UTC by ilius

2017-06-30 04:57 UTC, shurcooL commented on server.go
>  	}
You could consider taking the nested if/else if statement and merge it with the existing switch cases, like this:

```Go
switch err {
case err == nil:
	code = ssh_FX_OK
case err == io.EOF:
	code = ssh_FX_EOF
case os.IsPermission(err):
	code = ssh_FX_PERMISSION_DENIED
case os.IsNotExist(err):
	code = ssh_FX_NO_SUCH_FILE
}
```

You could even move the `ssh_FX_FAILURE` default value into the `default:` case, so all the logic for selecting code is in one place.

2017-06-30 10:48 UTC, taruti commented
Hello @ilius 

Like @shurcooL suggested, please refactor the switch. Thank you for the contribution, after that tweak I'll merge this PR.

2017-07-01 00:42 UTC, ilius commented
@taruti done

2017-07-01 00:51 UTC, dmitshur requested changes
I guess this repo doesn't have CI, does it? The current version won't compile. You'll get errors like:

```
invalid case os.IsPermission(err) in switch on err (mismatched types bool and error)
invalid case os.IsNotExist(err) in switch on err (mismatched types bool and error)
```

2017-07-01 00:51 UTC, shurcooL commented on server.go
>  	switch err {
This should become `switch {`.

2017-07-01 00:51 UTC, shurcooL commented on server.go
>  	case nil:
`case err == nil:`.

2017-07-01 00:51 UTC, shurcooL commented on server.go
>  	case io.EOF:
`case err == io.EOF:`.

2017-07-01 01:39 UTC, ilius commented
Sorry, fixed

2017-07-01 03:18 UTC, merged

2017-07-01 03:20 UTC, taruti commented
Thank you for the  contribution. Merged into master.